### ISSUE TITLE
Improve TAP Output

### ISSUE THREAD

**Issue by jamestalmage** [avajs/ava#723]
There are lots of open issues regarding TAP output:
- [x] #679 - TAP report prints tests titles above not ok message
- [ ] #399 - power-assert graph not shown in TAP output.
- [ ] #324 - Include individual assertions in the TAP output.
- [ ] #340 - Capture good assertion messages.
- [ ] #648 - include line number of passing tests in TAP output

Remaining todo's from https://github.com/sindresorhus/ava/pull/340#issuecomment-177008691
- [ ] Bring our tap output more inline with `node-tap`. Specifically, the yaml output for our errors. This should make the output from all the tap-mocha-reporters much nicer. For example, our errors currently have `expected` and `actual` properties, but the tap reporters prefer found and wanted. Also, we should use `stack-utils` to attach the `at` property (file name and line number of failure).
- [ ] Finish up work on `tap-emitter` and integrate into AVA. 
## 
### Notes:

We should be using the [TAP v14 draft specification](https://github.com/TestAnything/testanything.github.io/pull/36).

Note that the spec does not address what properties should be included in the [yaml blocks](https://github.com/isaacs/testanything.github.io/blob/tap14/tap-version-14-specification.md#yaml-blocks). In that case we should just emulate `node-tap` (see list item above for examples of properties we need to add).

**Comment by xjamundx** [comment]
Probably related to this is the fact that `ava tests/ --tap | tap-xunit > ava-results.xml` produces some invalid XML characters.

```
<testsuite name="calculator ESC[90mESC[2m›ESC[22mESC[39m actions ESC[90mESC[2m›ESC[22mESC[39m __tests__ ESC[90mESC[2m›ESC[22mESC[39m Actions.fetchOriginAmount ESC[90mESC[2m›ESC[22mESC[39m with no changes a noop function should be returned" tests="1" failures="0" errors="0">
```

**Comment by sotojuan** [comment]
@xjamundx Can you post the actual tests that are giving you the strange XML output? I just tried `tap-xunit` with some simple tests and it worked fine.

**Comment by xjamundx** [comment]
@sotojuan it needs to be in a sub-directory for example

```
test/test.js
test/horse/test.js
```

~/dev/paypal/p2pnodeweb (junit) $ ./node_modules/.bin/ava test  --tap | ./node_modules/.bin/tap-xunit

The issue (from what I can tell is the little  › arrows)

```
<?xml version="1.0"?>
<testsuites>
  <testsuite name="horse › test › this is ta thing" tests="1" failures="0" errors="0">
    <testcase name="#1 horse › test › this is ta thing"/>
  </testsuite>
  <testsuite name="test › this is ta thing" tests="1" failures="0" errors="0">
    <testcase name="#2 test › this is ta thing"/>
  </testsuite>
</testsuites>
```

**Comment by sotojuan** [comment]
Thanks for the feedback. I'll look into it later today.

**Comment by sindresorhus** [comment]
That's something the reporter should fix. We can't possible correctly escape our titles for every possible scenario.

**Comment by xjamundx** [comment]
Thanks for the tip @sindresorhus

**Comment by sindresorhus** [comment]
It seems we also incorrectly include some ansi escape codes in the title `ESC[90mESC[2m`. We should use [`strip-ansi`](https://github.com/chalk/strip-ansi) on the title in the tap reporter. @sotojuan Wanna do a PR for that?

(The actual issue is still that the reporter doesn't escape the title though)

**Comment by xjamundx** [comment]
Thanks for following up.

**Comment by sotojuan** [comment]
Opened #792 to help with the ANSI codes. Once it gets merged please test again with the latest master @xjamundx.

**Comment by xjamundx** [comment]
Can anyone confirm if the todo output is correct? The `tap-xunit` reporter is listing the todos as failures.

**Comment by sotojuan** [comment]
@xjamundx We fixed the ANSI escape codes—let us know how they are now.

**Comment by xjamundx** [comment]
Woohoo!

**Comment by novemberborn** [comment]
This issue isn't directly actionable. I'm starting to update open TAP-related issues with the `feature: tap reporter` instead.
